language: ruby
rvm:
  - 2.2.3
cache: bundler

before_install: 
  - gem update --system
  - bundle install
  - bundle exec rake db:migrate RAILS_ENV=test
  - bundle exec rake

after_success:
  - coveralls